export default [
  {
    login: "hallelujah",
    id: 64276,
    node_id: "MDQ6VXNlcjY0Mjc2",
    avatar_url: "https://avatars3.githubusercontent.com/u/64276?v=4",
    gravatar_id: "",
    url: "https://api.github.com/users/hallelujah",
    html_url: "https://github.com/hallelujah",
    followers_url: "https://api.github.com/users/hallelujah/followers",
    following_url: "https://api.github.com/users/hallelujah/following{/other_user}",
    gists_url: "https://api.github.com/users/hallelujah/gists{/gist_id}",
    starred_url: "https://api.github.com/users/hallelujah/starred{/owner}{/repo}",
    subscriptions_url: "https://api.github.com/users/hallelujah/subscriptions",
    organizations_url: "https://api.github.com/users/hallelujah/orgs",
    repos_url: "https://api.github.com/users/hallelujah/repos",
    events_url: "https://api.github.com/users/hallelujah/events{/privacy}",
    received_events_url: "https://api.github.com/users/hallelujah/received_events",
    type: "User",
    site_admin: false
  },
  {
    login: "YukyNawanjana",
    id: 46666601,
    node_id: "MDQ6VXNlcjQ2NjY2NjAx",
    avatar_url: "https://avatars0.githubusercontent.com/u/46666601?v=4",
    gravatar_id: "",
    url: "https://api.github.com/users/YukyNawanjana",
    html_url: "https://github.com/YukyNawanjana",
    followers_url: "https://api.github.com/users/YukyNawanjana/followers",
    following_url: "https://api.github.com/users/YukyNawanjana/following{/other_user}",
    gists_url: "https://api.github.com/users/YukyNawanjana/gists{/gist_id}",
    starred_url: "https://api.github.com/users/YukyNawanjana/starred{/owner}{/repo}",
    subscriptions_url: "https://api.github.com/users/YukyNawanjana/subscriptions",
    organizations_url: "https://api.github.com/users/YukyNawanjana/orgs",
    repos_url: "https://api.github.com/users/YukyNawanjana/repos",
    events_url: "https://api.github.com/users/YukyNawanjana/events{/privacy}",
    received_events_url: "https://api.github.com/users/YukyNawanjana/received_events",
    type: "User",
    site_admin: false
  }
]