export default {
  login: "Blondish",
  id: 42301781,
  node_id: "MDQ6VXNlcjQyMzAxNzgx",
  avatar_url: "https://avatars0.githubusercontent.com/u/42301781?v=4",
  gravatar_id: "",
  url: "https://api.github.com/users/Blondish",
  html_url: "https://github.com/Blondish",
  followers_url: "https://api.github.com/users/Blondish/followers",
  following_url: "https://api.github.com/users/Blondish/following{/other_user}",
  gists_url: "https://api.github.com/users/Blondish/gists{/gist_id}",
  starred_url: "https://api.github.com/users/Blondish/starred{/owner}{/repo}",
  subscriptions_url: "https://api.github.com/users/Blondish/subscriptions",
  organizations_url: "https://api.github.com/users/Blondish/orgs",
  repos_url: "https://api.github.com/users/Blondish/repos",
  events_url: "https://api.github.com/users/Blondish/events{/privacy}",
  received_events_url: "https://api.github.com/users/Blondish/received_events",
  type: "User",
  site_admin: false,
  name: "Olena",
  company: "JUNIOR FULL STACK MERN WEB DEVELOPER",
  blog: "",
  location: "Barcelona, Spain ",
  email: null,
  hireable: null,
  bio: null,
  twitter_username: null,
  public_repos: 20,
  public_gists: 0,
  followers: 2,
  following: 3,
  created_at: "2018-08-11T17:16:36Z",
  updated_at: "2020-10-07T19:45:34Z"
}